services:
  web:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=securenotes;Username=${DB_USERNAME};Password=${DB_PASSWORD}
    volumes:
      - ./DataProtection:/root/.aspnet/DataProtection  # Persist data protection keys
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: securenotes
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
