services:
  web:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=appdb;Username=appuser;Password=apppassword
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
